fix css styles
edx/frontend-app-logistration pull request #68
Opened 2021-01-05 00:42 UTC by uzairr

VAN-249

2021-01-06 07:44 UTC, waheedahmed requested changes

2021-01-06 07:44 UTC, waheedahmed commented on src/forgot-password/ForgotPasswordPage.jsx
> +                  className="btn-primary submit ml-0"
Remove the `submit` class instead of adding `ml-0`

2021-01-06 07:44 UTC, waheedahmed commented on src/logistration/LoginPage.jsx
> +          <div className="d-flex flex-column login-form-width">
I have removed these hardcoded widths on all forms in this https://github.com/edx/frontend-app-logistration/pull/69, these are causing issues with the responsiveness of the form on the smaller devices. Kindly remove these changes and rebase with the latest master branch.

2021-01-06 07:44 UTC, waheedahmed commented on src/logistration/_style.scss
> +.login-form-width{
Remove it.

2021-01-07 07:35 UTC, zainab-amir approved these changes

2021-01-07 11:05 UTC, merged